name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t oladockuser/portofolio .
      - name: Push image
        run:  
              docker login -u oladockuser -p ${{secret.REGISTRY_PASS}}
              docker push oladockuser/portofolio